const fs = require("node:fs");
const path = require("node:path");

function loadEnvFile(options = {}) {
  const cwd = options.cwd || process.cwd();
  const fileName = options.fileName || ".env.local";
  const filePath = path.isAbsolute(fileName) ? fileName : path.join(cwd, fileName);
  const override = Boolean(options.override);

  if (!fs.existsSync(filePath)) {
    return {
      loaded: false,
      filePath,
      count: 0
    };
  }

  const content = fs.readFileSync(filePath, "utf8");
  const lines = content.split(/\r?\n/);
  let count = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const equalIndex = trimmed.indexOf("=");
    if (equalIndex <= 0) continue;

    const key = trimmed.slice(0, equalIndex).trim();
    if (!key || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;

    let value = trimmed.slice(equalIndex + 1).trim();
    if ((value.startsWith("\"") && value.endsWith("\"")) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    if (!override && process.env[key] !== undefined) continue;
    process.env[key] = value;
    count += 1;
  }

  return {
    loaded: true,
    filePath,
    count
  };
}

function saveEnvFile(options = {}) {
  const cwd = options.cwd || process.cwd();
  const fileName = options.fileName || ".env.local";
  const filePath = path.isAbsolute(fileName) ? fileName : path.join(cwd, fileName);
  const values = options.values || {};
  const allowlist = Array.isArray(options.allowlist) && options.allowlist.length
    ? new Set(options.allowlist)
    : null;

  const existing = parseEnvFile(filePath);
  const merged = { ...existing };

  Object.entries(values).forEach(([key, value]) => {
    if (allowlist && !allowlist.has(key)) return;
    if (value === undefined) return;
    if (value === null) {
      delete merged[key];
      return;
    }
    merged[key] = String(value);
  });

  const orderedKeys = buildOrderedKeys(merged);
  const lines = [
    "# Auto-generated by /v1/system/config/save",
    "# You can edit this file manually.",
    ""
  ];

  orderedKeys.forEach((key) => {
    lines.push(`${key}=${merged[key]}`);
  });

  lines.push("");
  fs.writeFileSync(filePath, lines.join("\n"), "utf8");

  return {
    saved: true,
    filePath,
    count: orderedKeys.length
  };
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, "utf8");
  const lines = content.split(/\r?\n/);
  const parsed = {};

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const equalIndex = trimmed.indexOf("=");
    if (equalIndex <= 0) continue;
    const key = trimmed.slice(0, equalIndex).trim();
    if (!key || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let value = trimmed.slice(equalIndex + 1).trim();
    if ((value.startsWith("\"") && value.endsWith("\"")) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    parsed[key] = value;
  }

  return parsed;
}

function buildOrderedKeys(envMap) {
  const preferred = [
    "MODEL_PROVIDER",
    "MODEL_NAME",
    "MODEL_API_KEY",
    "OPENAI_API_KEY",
    "GEMINI_API_KEY",
    "MODEL_BASE_URL",
    "MICROPAGE_ADAPTER_MODE",
    "MICROPAGE_API_BASE",
    "MICROPAGE_API_TOKEN",
    "MICROPAGE_API_PROFILE_FILE",
    "MICROPAGE_API_ENDPOINTS_JSON",
    "MICROPAGE_API_HEALTH_PATH",
    "ENABLE_REAL_AUTO_PUBLISH",
    "AUTOPUBLISH_TENANT_ALLOWLIST"
  ];

  const remaining = Object.keys(envMap).filter((key) => !preferred.includes(key)).sort();
  return [...preferred.filter((key) => envMap[key] !== undefined), ...remaining];
}

module.exports = {
  loadEnvFile,
  saveEnvFile
};
